Repository corca-ai/adcio_android_plugins, pull requests merged in 2023-09, with the labels that each got.

#8 add module description
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/exception/AnalyticsException.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/feature/AdcioAnalytics.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/feature/AdcioAnalyticsHistory.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/feature/AdcioImpressionDetector.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/exception/PlacementException.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/network/PlacementUrl.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/network/data/request/SuggestionsRequest.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/network/remote/PlacementRemote.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/network/service/PlacementService.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ai/corca/adcio_android_plugins/AdcioAndroidPluginsApplication.kt
  app/src/main/java/ai/corca/adcio_android_plugins/MainActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/AnalyticsActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/AnalyticsSuggestionListAdapter.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/utils/MockProduct.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/utils/MockProductDiffUtilCallback.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/utils/MockProductListAdapter.kt
  app/src/main/java/ai/corca/adcio_android_plugins/placement/PlacementActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/placement/utils/Production.kt
  app/src/main/java/ai/corca/adcio_android_plugins/placement/utils/SuggestionListAdapter.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/MockActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/adapter/CategoryAdapter.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/adapter/ProductAdapter.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/adapter/model/Product.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/adapter/util/CategoryDiffUtilCallback.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/adapter/util/ProductDiffUtilCallback.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/fragment/HomeFragment.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/fragment/ListFragment.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/fragment/RecommendFragment.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/utils/SampleData.kt
  app/src/main/java/ai/corca/adcio_android_plugins/usecases/mockapp/vm/HomeViewModel.kt
  app/src/main/res/layout/activity_analytics.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mock.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_mock_product.xml
  app/src/main/res/layout/item_product.xml
  app/src/main/res/layout/item_production.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature request

#7 Feature/update_modules_document
  adcio_agent/README.md
  adcio_agent/src/main/java/ai/corca/adcio_agent/agent/AgentClient.kt
  adcio_agent/src/main/java/ai/corca/adcio_agent/layout/AdcioAgentLayout.kt
  adcio_agent/src/main/java/ai/corca/adcio_agent/provider/AdcioAgent.kt
  adcio_agent_compose/README.md
  adcio_agent_compose/src/main/java/ai/corca/adcio_agent_compose/agent/AgentClient.kt
  adcio_agent_compose/src/main/java/ai/corca/adcio_agent_compose/provider/AdcioAgentCompose.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ai/corca/adcio_android_plugins/agent/ui/ComposeActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/agent/ui/SecondActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/agent/ui/XmlActivity.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/activity_second.xml
  app/src/main/res/layout/activity_xml.xml
Labels: documentation, feature request

#10 Feature/files_to_upload_mavencentral
  adcio_agent/build.gradle.kts
  adcio_agent_compose/build.gradle.kts
  adcio_analytics/build.gradle.kts
  adcio_placement/build.gradle.kts
  build.gradle.kts
  scripts/publish-module.gradle
  scripts/publish-root.gradle
Labels: feature request

#11 write document (README, KDoc)
  README.md
  adcio_agent/README.md
  adcio_agent/src/main/java/ai/corca/adcio_agent/agent/AgentClient.kt
  adcio_agent/src/main/java/ai/corca/adcio_agent/provider/AdcioAgent.kt
  adcio_agent_compose/README.md
  adcio_agent_compose/src/main/java/ai/corca/adcio_agent_compose/agent/AgentClient.kt
  adcio_agent_compose/src/main/java/ai/corca/adcio_agent_compose/provider/AdcioAgentCompose.kt
  adcio_analytics/README.md
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/AnalyticsUrl.kt
  adcio_placement/README.md
  adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/network/PlacementUrl.kt
  app/src/main/java/ai/corca/adcio_android_plugins/agent/ui/ComposeActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/agent/ui/XmlActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/AnalyticsActivity.kt
Labels: documentation

#14 Feature/change compose agentname
  adcio_agent_compose/build.gradle.kts
  adcio_agent_compose/src/main/java/ai/corca/adcio_agent_compose/agent/AgentClient.kt
  app/src/main/java/ai/corca/adcio_android_plugins/agent/ui/ComposeActivity.kt
Labels: feature request

#20 0.1.0 hotfix suggestion example code
  app/src/main/java/ai/corca/adcio_android_plugins/placement/PlacementActivity.kt
Labels: documentation

#21 build: change plugin dependency method
  app/build.gradle.kts
Labels: bug

#23 Feature/implement_analytics_pageview
  adcio_agent/build.gradle.kts
  adcio_agent_compose/build.gradle.kts
  adcio_analytics/build.gradle.kts
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/feature/AdcioAnalytics.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/mapper/AnalyticsMapper.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/model/AnalyticsPageViewOption.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/AnalyticsUrl.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/data/pageview/AnalyticsPageViewRequest.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/remote/AnalyticsRemote.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/service/AnalyticsService.kt
  adcio_core/.gitignore
  adcio_core/build.gradle.kts
  adcio_core/consumer-rules.pro
  adcio_core/proguard-rules.pro
  adcio_core/src/main/AndroidManifest.xml
  adcio_core/src/main/java/com/corcaai/adcio_core/error/IsNeedClientIdException.kt
  adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioInfo.kt
  adcio_placement/build.gradle.kts
  adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
  adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioSuggestionInfo.kt
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/ai/corca/adcio_android_plugins/MainActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/AnalyticsActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/core/CoreActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/placement/PlacementActivity.kt
  app/src/main/res/layout/activity_core.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_placement.xml
  settings.gradle.kts
Labels: feature request

#25 Feature/implement_core_module
  adcio_core/build.gradle.kts
  adcio_core/src/androidTest/java/com/corcaai/AdcioCoreTest.kt
  adcio_core/src/main/java/com/corcaai/adcio_core/error/IsNeedClientIdException.kt
  adcio_core/src/main/java/com/corcaai/adcio_core/error/NotInitializedException.kt
  adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioCore.kt
  adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioInfo.kt
Labels: bug

#27 Feature/change suggestion getid method to core format
  adcio_placement/build.gradle.kts
  adcio_placement/src/main/java/ai/corca/adcio_placement/feature/AdcioPlacement.kt
Labels: feature request

#29 refactor: used the parameter clientid is null, core clientid in the agent call url
  adcio_agent/src/main/java/ai/corca/adcio_agent/agent/AgentClient.kt
  adcio_agent/src/main/java/ai/corca/adcio_agent/provider/AdcioAgent.kt
  adcio_agent_compose/src/main/java/ai/corca/adcio_agent_compose/agent/AgentClient.kt
Labels: feature request

#30 Feature/fix build error
  adcio_agent/build.gradle.kts
  adcio_agent_compose/build.gradle.kts
  adcio_analytics/build.gradle.kts
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/model/AnalyticsPageViewOption.kt
  adcio_placement/build.gradle.kts
  app/build.gradle.kts
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/AnalyticsActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/core/CoreActivity.kt
Labels: bug

#35 hotfix/clean_adjust_recyclerview
  app/src/main/res/layout/activity_placement.xml
Labels: bug

#36 Feature/Update Exception in id setter if notinit
  adcio_core/src/androidTest/java/com/corcaai/AdcioCoreTest.kt
  adcio_core/src/main/java/com/corcaai/adcio_core/feature/AdcioCore.kt
Labels: feature request

#38 docs: update core readme.md
  adcio_core/README.md
Labels: documentation

#39 Feature/refactor pageview argumentparam
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/feature/AdcioAnalytics.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/mapper/AnalyticsMapper.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/remote/AnalyticsRemote.kt
Labels: feature request

#46 docs: update analytics readme
  adcio_analytics/README.md
Labels: documentation

#47 Feature/Analytics AddToCart & Update Scheme
  adcio_analytics/src/androidTest/java/ai/corca/adcio_analytics/ExampleInstrumentedTest.kt
  adcio_analytics/src/main/AndroidManifest.xml
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/feature/AdcioAnalytics.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/mapper/AnalyticsMapper.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/AnalyticsUrl.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/data/AnalyticsPerformanceRequest.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/data/event/AnalyticsAddToCartRequest.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/data/event/AnalyticsPageViewRequest.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/data/event/AnalyticsPurchaseRequest.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/remote/AnalyticsRemote.kt
  adcio_analytics/src/main/java/ai/corca/adcio_analytics/network/service/AnalyticsService.kt
  adcio_analytics/src/test/java/ai/corca/adcio_analytics/ExampleUnitTest.kt
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/AnalyticsActivity.kt
Labels: feature request

#54 Feature/appmodule plugin versionup
  app/build.gradle.kts
  app/src/main/java/ai/corca/adcio_android_plugins/analytics/AnalyticsActivity.kt
  app/src/main/java/ai/corca/adcio_android_plugins/placement/PlacementActivity.kt
Labels: feature request

#55 Feature/update agent readme
  adcio_agent/README.md
  adcio_agent_compose/README.md
Labels: documentation

#56 Feature/update changelog
  README.md
  adcio_agent/CHANGELOG.md
  adcio_agent_compose/CHANGELOG.md
  adcio_analytics/CHANGELOG.md
  adcio_core/CHANGELOG.md
  adcio_placement/CHANGELOG.md
Labels: documentation
